### ISSUE TITLE
train.pyの実行エラー

### ISSUE THREAD

**Issue by KAZUHA0604** [Hiroshiba/become-yukarin#38]
train.pyを動かすとこのようなエラーがはきだされます。
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    parser.add_argument('config_json_path', type=Path)
NameError: name 'parser' is not defined

**Comment by KAZUHA0604** [comment]
上記は私のミスと判明
File "train.py", line 82, in <module>
    save_args(arguments, arguments.output)
  File "/usr/local/lib/python3.6/dist-packages/chainerui/utils/save_args.py", line 33, in save_args
    json.dump(args, f, indent=4)
  File "/usr/lib/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'PosixPath' is not JSON serializable
現在はここの問題で止まっています。
