### ISSUE TITLE
extract_acoustic_feature.py時のエラー

### ISSUE THREAD

**Issue by KAZUHA0604** [Hiroshiba/become-yukarin#40]
Traceback (most recent call last):
  File "scripts/extract_acoustic_feature.py", line 206, in <module>
    main()
  File "scripts/extract_acoustic_feature.py", line 193, in main
    assert len(paths1) == len(paths2)
AssertionError
のようなエラーがでるようになってしまいました。
何が原因でしょうか？

**Comment by KAZUHA0604** [comment]
用意していた200コの音声データを名前順に1～100までにした場合動作しました。
しかし、101～200のみで動かそうとした場合動きませんでした。

**Comment by KAZUHA0604** [comment]
ファイル数の違いがこのエラーを招いていたことが判明しました。
