### ISSUE TITLE
第一段階の学習でエラーが出てしまう

### ISSUE THREAD

**Issue by BURI55** [Hiroshiba/become-yukarin#51]
第一段階の学習をかけたところ以下のエラーが出ました　何が悪いのでしょうか？

python train.py dat/config.json dat/model/yukari_1st
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from become_yukarin.config.config import create_from_json
  File "/home/buri/become-yukarin/become_yukarin/__init__.py", line 6, in <module>
    from .vocoder import RealtimeVocoder
  File "/home/buri/become-yukarin/become_yukarin/vocoder.py", line 3, in <module>
    from world4py.native import structures, apidefinitions, utils
  File "/home/buri/.pyenv/versions/3.6.3/lib/python3.6/site-packages/world4py/native/__init__.py", line 6, in <module>
    from world4py.native import apis, tools, utils, structures
  File "/home/buri/.pyenv/versions/3.6.3/lib/python3.6/site-packages/world4py/native/apis.py", line 6, in <module>
    from world4py.native import apidefinitions, structures, utils
  File "/home/buri/.pyenv/versions/3.6.3/lib/python3.6/site-packages/world4py/native/apidefinitions.py", line 7, in <module>
    from world4py.native import structures, instance
  File "/home/buri/.pyenv/versions/3.6.3/lib/python3.6/site-packages/world4py/native/instance.py", line 9, in <module>
    _WORLD = ctypes.cdll.LoadLibrary(_WORLD_LIBRARY_PATH)
  File "/home/buri/.pyenv/versions/3.6.3/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/home/buri/.pyenv/versions/3.6.3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/buri/.pyenv/versions/3.6.3/lib/python3.6/site-packages/world4py/libworld.so: cannot open shared object file: No such file or directory

**Comment by YoshikazuOota** [comment]
attic です。

エラーの内容は 『WORLD4py のライブラリのファイルが開けない（存在しない）』とのことです。
WORLD4pyのインストールに失敗している可能性があります。

pip uninstall world4py

で、一度 world4pyの削除を行います。
その後、再びWORLD4py ディレクトリでインストールをおこなってみてください。
その際には、--no-cache-dir と -I を付けた方が安全です。
これは、前回のインストールのキャッシュデータを破棄して、インストールする方法です。

pip --no-cache-dir install -I world4py

このエラーを踏んだことがないので、推測の対応になりますが、お試しください。

以上、よろしくお願いいたします。


2019年6月9日(日) 21:58 BURI55 <notifications@github.com>:

**Comment by Hiroshiba** [comment]
学習段階でworld4pyが必須になっていたので修正しました。
https://github.com/Hiroshiba/become-yukarin/commit/b5fd5dad7ddb43006dcdf9f97c30ba2212ad0cc1

一度issueを閉じますが、また同様のエラーが出た場合は再度openして質問してください。
