### ISSUE TITLE
続　第一段階の学習でエラーが出てしまう

### ISSUE THREAD

**Issue by BURI55** [Hiroshiba/become-yukarin#52]
アドバイスに従って、WORLD４pyの入れ直しやvocorder.pyの入れ直しを行ってみましたが
エラーは減りましたがやはり出ます。
buri@buri-Diginnos-PC:~/become-yukarin$ python train.py dat/config.json dat/model/yukari_1st
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from become_yukarin.config.config import create_from_json
  File "/home/buri/become-yukarin/become_yukarin/__init__.py", line 6, in <module>
    from .vocoder import RealtimeVocoder
  File "/home/buri/become-yukarin/become_yukarin/vocoder.py", line 3, in <module>
    from world4py.native import structures, apidefinitions, utils
ModuleNotFoundError: No module named 'world4py'

**Comment by BURI55** [comment]
やはりWORLD4pyのインストールミスでした。音響特徴量の切り出しからうまく行ってなかったようです
